version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://blog_user:blog_password@db:3306/blog_db
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - blog-network
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 10 &&
        python init_db.py &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  blog-network:
    driver: bridge 